### ISSUE TITLE
App has stopped error

### ISSUE THREAD

**Issue by suvskr** [DenisMondon/material-design-library#1]
When I try to open Navigation drawer with account I see message "Unfortunately, *yourapp* has stopped".
Lenovo S750, Android 4.2.1.

**Comment by DenisMondon** [comment]
Hi! Thank you for your issue!
Can you give me your class that extends NavigationDrawerActivity?

I will try to know why it stops.

Thank you.

Denis

**Comment by suvskr** [comment]
I don't use your library yet.
I think error in your sample app.
May be here:
material-design-library/sample/src/main/java/com/blunderer/materialdesignlibrary/sample/navigationdrawers/NavigationDrawerWithAccountsActivity.java

**Comment by suvskr** [comment]
By the way, I have question: where you get material design animation and pngs?
I think they must be in sdk api 21, but I can't find them.

**Comment by DenisMondon** [comment]
I think I found the error. Thank you, I will release the new apk soon.
What do you mean by animation? Like button pressed on Android Lollipop? Like Activity transition? :)

**Comment by suvskr** [comment]
OK, I tell you as soon update the app.
Not only button.
I mean something like menu_button-left_arrow animation when I open navigation drawer.

**Comment by DenisMondon** [comment]
Oh yeah it is on api 21 but I use it with the appcompat-v7.

**Comment by suvskr** [comment]
It's work. )
Thank you.
