### ISSUE TITLE
Image url

### ISSUE THREAD

**Issue by akaramires** [DenisMondon/material-design-library#11]
How can I implement lazy loading images from url to CardView?

**Comment by DenisMondon** [comment]
Hi!

I will think about it ;)
But I think it's a great idea!

Thank you

Denis

**Comment by akaramires** [comment]
hi, thx for answer. 
the ideal would be integration with glide (https://github.com/bumptech/glide)

**Comment by DenisMondon** [comment]
This one is good but the min API version is 10 and mine is 9 :'(
I think I will use universal image loader instead... https://github.com/nostra13/Android-Universal-Image-Loader

**Comment by DenisMondon** [comment]
Hi!

Finally, you can load an image from a url to put it on a cardview! :)
Just do this:
```xml
<com.blunderer.materialdesignlibrary.views.CardView
        android:id="@+id/cardview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:mdl_title="CardView"
        app:mdl_description="A Basic CardView"
        app:mdl_normalButton="Normal"
        app:mdl_highlightButton="Highlight"
        app:mdl_imagePosition="top"
        app:mdl_imageUrl="http://your_url_image.jpg"/>
```
(Just update the library version => 2.0.1)

Denis

**Comment by akaramires** [comment]
thx, man!
