### ISSUE TITLE
How to add Navigation Up Button within activity's action bar?

### ISSUE THREAD

**Issue by allenxuan** [DenisMondon/material-design-library#13]
When I use my own activity which does not extend any of the material activity classes in the lib，it turns out there is no action bar. When I build a material activity with the lib, action bar emerges, but no Navigation Up Button there within the action bar， how can I add one?

**Comment by allenxuan** [comment]
Sorry, I'm a novice to android development, and I've figured it out myself. Apologize!

**Comment by DenisMondon** [comment]
Good! :) Yeah I use a NoActionBar Theme so you can't have the ActionBar in your own Activity.
The way to do this is to add a ToolBar (https://developer.android.com/reference/android/support/v7/widget/Toolbar.html) in your xml layout :)

Tell me if it is OK :)

Denis

**Comment by allenxuan** [comment]
Thanks a lot, Denis. It works, but it's not that ideal for the reason that API level of Toolbar is too high(21) to be backward compatible.

**Comment by DenisMondon** [comment]
No it is also added in the v7 support :)
So you can add it like that:
<android.support.v7.widget.Toolbar
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:minHeight="?attr/actionBarSize"
        android:background="?attr/colorPrimary"/>

:)

Denis

**Comment by allenxuan** [comment]
wow, so many Toolbars, now I get it, and it works well. I've learned a lot from you. Thanks for your patience, Denis. o(^▽^)o

**Comment by DenisMondon** [comment]
:D You're welcome :) Close the issue if you don"t have other questions :)

Denis

**Comment by allenxuan** [comment]
Hi, Denis. I construct a material drawer activity which contains a
fragment. When I'm in this fragment, how can I get its parent activity? Is
it the drawer activity? It seem not.

**Comment by DenisMondon** [comment]
Just do this in your Fragment:
```java
FragmentActivity activity = getActivity();
if (activity instanceof NavigationDrawerActivity) {
      NavigationDrawerActivity navigationDrawerActivity = (NavigationDrawerActivity) activity;
      // navigationDrawerActivity.callSomeMethod();
}
```

**Comment by allenxuan** [comment]
I’ve got it ! You are so patient, and I wanna be as brilliant as you
someday.(○'ω'○)

**Comment by allenxuan** [comment]
Hi, Denis! Is it Possible to dynamically add or delete items in
NavigationDrawerActivity with your lib?

2015-05-30 1:16 GMT+08:00 黄玄羿 <allenxuan@gmail.com>:

> I’ve got it ! You are so patient, and I wanna be as brilliant as you
> someday.(○'ω'○)

**Comment by DenisMondon** [comment]
No you can't but you can do it by yourself :) I don't know if I will put this feature in my lib. Maybe one day ;)

**Comment by haydarai** [comment]
So how to actually create navigation up button?
Because the NavigationDrawerActivity will force me to use Fragment, but I can't call getSupportActionBar inside fragment, isn't it?
So how can I solve this problem?
Thanks Dennis Mondon, your library really save my time :)

**Comment by haydarai** [comment]
I figured out how to create my own action bar at fragment. But the thing is there will be two action bar (action bar created in fragment) and action bar (action bar created because of this library). So how I to make only the action bar created in fragment is available?
