### ISSUE TITLE
Failed gradle building

### ISSUE THREAD

**Issue by skobelev-dmitriy** [DenisMondon/material-design-library#15]
Errors while bildind app in Studio:
AAPT err(1702938490): ....\AndroidStudioProjects\Viruchatel\app\build\intermediates\exploded-aar\com.blunderer\materialdesignlibrary\2.0.0\res\drawable-mdpi-v4\ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1956559943): ...\AndroidStudioProjects\Viruchatel\app\build\intermediates\exploded-aar\com.blunderer\materialdesignlibrary\2.0.0\res\drawable-hdpi-v4\ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(179930750):...\AndroidStudioProjects\Viruchatel\app\build\intermediates\exploded-aar\com.blunderer\materialdesignlibrary\2.0.0\res\drawable-xhdpi-v4\ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
....
...\AndroidStudioProjects\Viruchatel\app\build\intermediates\res\debug\drawable-hdpi-v4\vpi__tab_selected_focused_holo.9.png: error: Duplicate file.
...\AndroidStudioProjects\Viruchatel\app\build\intermediates\res\debug\drawable-hdpi\vpi__tab_selected_focused_holo.9.png: Original is here. The version qualifier may be implied.

This errors starts after I add dependency in  build.gradle.

**Comment by DenisMondon** [comment]
What dependency are you trying to add?

**Comment by skobelev-dmitriy** [comment]
compile 'com.blunderer:materialdesignlibrary:2.0.0'

**Comment by skobelev-dmitriy** [comment]
AAPT err(1702938490): C:\Users\Дмитрий\AndroidStudioProjects\Viruchatel\app\build\intermediates\exploded-aar\com.blunderer\materialdesignlibrary\2.0.0\res\drawable-mdpi-v4\ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1956559943): C:\Users\Дмитрий\AndroidStudioProjects\Viruchatel\app\build\intermediates\exploded-aar\com.blunderer\materialdesignlibrary\2.0.0\res\drawable-hdpi-v4\ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(179930750): C:\Users\Дмитрий\AndroidStudioProjects\Viruchatel\app\build\intermediates\exploded-aar\com.blunderer\materialdesignlibrary\2.0.0\res\drawable-xhdpi-v4\ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

**Comment by DenisMondon** [comment]
Can you give me the other libraries that you have?

**Comment by DenisMondon** [comment]
I think there are duplicates libraries

**Comment by skobelev-dmitriy** [comment]
compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:cardview-v7:22.2.0'
    compile 'com.viewpagerindicator:library:2.4.1@aar'
    compile 'com.blunderer:materialdesignlibrary:2.0.0'

**Comment by DenisMondon** [comment]
Try removing the first three libraries (they already are in my library). Tell me.

**Comment by skobelev-dmitriy** [comment]
Thanks a lot. Everything worked !!!!!

**Comment by DenisMondon** [comment]
Good :D
