### ISSUE TITLE
Navigation Drawer with custom layout

### ISSUE THREAD

**Issue by jaysavsani** [DenisMondon/material-design-library#19]
Hey Denis, 
I found this library very useful for beginners and I've already integrated this in my project. But I'm getting problem in integrating of navigation drawer with my own custom layout. According to doc we can't use setContentView() for custom layout instead we've to use getContentView() but it's only available to Activity and not for NavigationDrawerActivity.
I want show my own layout with search result in grid when user selects suggestion from autocompletion actionbar search.
 What I'm doing wrong here? Can you help to solve this?

**Comment by DenisMondon** [comment]
Hi!

There is no getContentView() for NavigationDrawerActivity.
You have to implement getNavigationDrawerTopHandler().

Look at my example here: https://github.com/DenisMondon/material-design-library/blob/master/sample/src/main/java/com/blunderer/materialdesignlibrary/sample/navigationdrawers/NavigationDrawerActivity.java

Hope it helped!

Denis

**Comment by jaysavsani** [comment]
Denis,
Thank you for quick reply. As far as I understand I've to use fragment instead of my own Activity right.? I can use my fragment without extending any of your fragment and where I can use my custom layout.

**Comment by DenisMondon** [comment]
You have to create a fragment (your own or an extended of mine) and add it in getNavigationDrawerTopHandler().
