### ISSUE TITLE
Configurable hamburger icon color

### ISSUE THREAD

**Issue by sonph** [DenisMondon/material-design-library#2]
First thank you for this useful library.

Second, is it possible to change the hamburger/drawer icon color to a different color (say, white) since I have a dark theme and the dark hamburger icon doesn't quite fit in.

Also I'd suggest changing methods to `protected` so people can override what they need to change. For example I had to clone the source code and add a `closeDrawer()` method to close the drawer when I launch a new Activity so that it stays closed when user comes back.

**Comment by DenisMondon** [comment]
Hi sonph!!

Thank you for your issue! :)
For the hamburger icon, I did not have time to look how it works but for the moment, you can have it in white or black by doing this:
White: <style name="AppTheme" parent="@style/MaterialDesignLibraryTheme">
Black: <style name="AppTheme" parent="@style/MaterialDesignLibraryTheme.Light">

For your second point, you are right. In the next release, you will be able to get the NavigationDrawer, close it, open it from your activity/fragment. (It will be released tonight I think).

void closeNavigationDrawer()
void openNavigationDrawer()
DrawerLayout getNavigationDrawer()

If you have other questions, ask me ;)

Thank you again.
Denis

**Comment by sonph** [comment]
After doing some research I was able to change the color by adding `drawerArrowStyle` (I didn't use your theme because I already use some other theme for my existing project)

    <style name="AppTheme" ...>
        <item name="drawerArrowStyle">@style/DrawerIconStyle</item>
    </style>

    <style name="DrawerIconStyle" parent="Widget.AppCompat.DrawerArrowToggle">
        <item name="color">@android:color/white</item>
    </style>

**Comment by DenisMondon** [comment]
Thank you very much for your help!

Denis
