### ISSUE TITLE
Implementing CardView in a fragment

### ISSUE THREAD

**Issue by Brahim1992** [DenisMondon/material-design-library#20]
Hi,
I want to implement a list of the CardView Component in a fragment.
But i'm facing this exception : android.view.InflateException: Binary XML file line #8: Error inflating class com.blunderer.materialdesignlibrary.views.CardView

Is it necessary to use the Card in an Activity ?

Thanks

**Comment by DenisMondon** [comment]
Hi!

I have just tested and it works perfectly! :)
I have a ViewPagerActivity with 1 page.
This page is a ListViewFragment. In this fragment, I have my Apapter to show 3 CardViews.

Here is what I get:

![screenshot_2015-07-02-23-29-02](https://cloud.githubusercontent.com/assets/1906100/8488351/683eff08-2112-11e5-9817-d5e19eeebb63.png)

**Comment by RrArdian** [comment]
Hai Dennis,
thats great, thats what I need.. i just try to make cardview like that, but I have a problem, can you show me the script in your adapter to show 3 cardview? thanks

**Comment by dadja** [comment]
Hi Denis hi all,
sorry for using this thread to ask another question; i would like to know
if its possible custom the size of the text inside tabs . and if so which
method do we use to do so. Thanks

2015-07-02 21:31 GMT+00:00 Denis Mondon <notifications@github.com>:

> Hi!
>
> I have just tested and it works perfectly! :)
> I have a ViewPagerActivity with 1 page.
> This page is a ListViewFragment. In this fragment, I have my Apapter to
> show 3 CardViews.
>
> Here is what I get:
>
> [image: screenshot_2015-07-02-23-29-02]
> <https://cloud.githubusercontent.com/assets/1906100/8488351/683eff08-2112-11e5-9817-d5e19eeebb63.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DenisMondon/material-design-library/issues/20#issuecomment-118173407>
> .
>



-- 


Best Regards Dadja Matiasso BASSOU


Sofware Engineer
Indie Game Developer
Tel:+221774627966
*youtube channel :* http://www.youtube.com/reptx
E*mail:* bassoudadja@gmail.com <email%3Abassoudadja@gmail.com>
*Skype:* apocalypse003
Twitter:@Reptx

**Comment by DenisMondon** [comment]
Yeah RrArdian ;)

Here is my Fragment:
```java
public class CardViewNormalTestFragment
        extends com.blunderer.materialdesignlibrary.fragments.ListViewFragment {

    @Override
    public ListAdapter getListAdapter() {
        return new TestAdapter(getActivity(), R.layout.testcardview);
    }

    @Override
    public boolean useCustomContentView() {
        return false;
    }

    @Override
    public int getCustomContentView() {
        return 0;
    }

    @Override
    public boolean pullToRefreshEnabled() {
        return false;
    }

    @Override
    public int[] getPullToRefreshColorResources() {
        return new int[0];
    }

    @Override
    public void onRefresh() {
    }

    @Override
    public void onItemClick(AdapterView<?> adapterView, View view, int position, long l) {
    }

    @Override
    public boolean onItemLongClick(AdapterView<?> adapterView, View view, int position, long l) {
        return false;
    }

    private class TestAdapter extends ArrayAdapter<String> {

        public TestAdapter(Context context, int resource) {
            super(context, resource);
        }

        @Override
        public int getCount() {
            return 3;
        }

        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
            if (convertView == null) {
                convertView = LayoutInflater.from(getContext()).inflate(R.layout.testcardview, parent, false);
            }
            return convertView;
        }
    }
}
```

Denis

**Comment by DenisMondon** [comment]
Hi dadja!

Yeah in your **ViewPagerWithTabsActivity**, just write these lines:
(there is a bug in the PagerSlidingTabStrip library, so you have to write also the first line)
```java
mViewPagerTabs.setTabBackground(0);
mViewPagerTabs.setTextSize(50);
```
Denis

**Comment by Brahim1992** [comment]
Hi Denis,
Thanks for your help, now it works for me.
But now i want to add to the ListViewFragment layout(wich contains the ListView) a view like Button, so how i can infalte the view wich is automatically generated with the library.

Thanks so much.

**Comment by DenisMondon** [comment]
So you have a button in each ListView item?
To access to each button, you have to find them in your adapter.

In your ListAdapter file:

```java
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        ViewHolder holder;

        if (convertView == null) {
            convertView = LayoutInflater
                    .from(getContext())
                    .inflate(R.layout.your_cardview_layout, parent, false);

            int itemsTextStyle = mNavigationDrawerStyleHandler.getTopItemsTextStyle();
            int sectionsTextStyle = mNavigationDrawerStyleHandler.getTopSectionsTextStyle();

            holder = new ViewHolder();
            holder.button = (Button) convertView.findViewById(R.id.cardview_button);
            convertView.setTag(holder);
        } else holder = (ViewHolder) convertView.getTag();

        holder.button.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                        // do what you want here
                }
        });

        return convertView;
    }

    private class ViewHolder {

        private Button button;

    }
```

Denis

**Comment by Brahim1992** [comment]
Thanks for your quick reply, but i want to add a button to the listView layout not for the list items, so how i can do it ?

**Comment by DenisMondon** [comment]
Oh I understood :)

You have to use the custom view: write this in your ListViewFragment:
```java
    @Override
    public boolean useCustomContentView() {
        return true;
    }

    @Override
    public int getCustomContentView() {
        return R.layout.your_custom_view;
    }
```
R.layout.your_custom_view has to contain your own ListView and your Button.

Does that solve your problem?

Denis

**Comment by Brahim1992** [comment]
Yep it works now, firstly the interface contained just the button with empty List, but i overrided the onCreateView methode and set the adapter to the listView.

Thanks so much for your time.

**Comment by DenisMondon** [comment]
Does your listview have @android:id/list as id?

**Comment by Brahim1992** [comment]
aaah ok i change the id to @android:id/list and it works without setting the adapter manually.
Sorry to say so, but i still have a question is that if i want to work with GridView instead of ListView, what should i do?

Thanks

**Comment by DenisMondon** [comment]
It is not in the library yet.
If you want to do this right now, you have to write all the code (not using my lib).
But I think later, I will add more Activities and Fragments (GridView and others).

Denis

**Comment by Brahim1992** [comment]
ok, i think  will do it for my own.
Thank you so much for what you have done for me, i really appreciate it (y).

**Comment by DenisMondon** [comment]
You're welcome ;)
