### ISSUE TITLE
Apdate Title of ActionBar 

### ISSUE THREAD

**Issue by alessandropiola** [DenisMondon/material-design-library#21]
Hi Denis,
you make my app beautiful in 5 second.
I have a questiond.
I have added a NavigationDrawer, and in a fragment i have a button that change the fragment loaded with on other.
..
        ImageButton ibSet = (ImageButton) view.findViewById(R.id.ibSettings);
        ibSet.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Create new fragment and transaction
                Fragment newFragment = new SettingFragment();
                FragmentTransaction transaction = getFragmentManager().beginTransaction();

                // Replace whatever is in the fragment_container view with this fragment,
                // and add the transaction to the back stack if needed
                transaction.replace(R.id.fragment_container, newFragment);
                transaction.addToBackStack(null);
                transaction.commit();

            }
        });
..
My goal is change the name title of action bar.
How can i do that?

**Comment by DenisMondon** [comment]
Hi!

Try adding this in your code:
getSupportActionBar().setTitle(title);
