### ISSUE TITLE
How to set image programatilly to CardView ?

### ISSUE THREAD

**Issue by MrThiago** [DenisMondon/material-design-library#22]
I have tried: mCardView.setImageBitmap(bitmap);

I want to take a photo on the camera and load the image into this 

<com.blunderer.materialdesignlibrary.views.CardView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:mdl_title="CardView"
        app:mdl_description="A Left Image CardView"
        app:mdl_normalButton="Normal"
        app:mdl_highlightButton="Highlight"
        app:mdl_imagePosition="left"
        app:mdl_image="@drawable/image" />

Can you help pls. thank you

**Comment by DenisMondon** [comment]
Hi!

You have to convert your bitmap to a drawable and set the drawable to the cardview:
Drawable d = new BitmapDrawable(getResources(), bitmap);
mCardView.setImageDrawable(your_image);

**Comment by MrThiago** [comment]
Thank you
