### ISSUE TITLE
Change tab color

### ISSUE THREAD

**Issue by harishannam** [DenisMondon/material-design-library#23]
Is there a way to change the ViewPagerTab colors or the Tab marker color, font color etc.

**Comment by DenisMondon** [comment]
Hi!

In your ViewPagerWithTabsActivity, just write this line:

```java
mViewPagerTabs.setBackgroundColor(Color.GRAY);
```

Denis

**Comment by harishannam** [comment]
Thanks alot for your reply :+1:
