### ISSUE TITLE
[NavigationDrawer] Fragment title bug after screen rotation

### ISSUE THREAD

**Issue by robertwgh** [DenisMondon/material-design-library#3]
**How to reproduce the issue:**
1. Start material design library demo app (assume the orientation is portrait). Title is "Fragment Listview" right now.
2. Rotate screen to landscape.
3. pull out navi drawer. Title becomes "Material Design Library".
4. Close navi drawer. Title stays at "Material Design Library"
5. Rotate back to portrait mode. Title is "Fragment ListView".
6. Pull out navi drawer, Title becomes "Material Design Library", and never change back, util you choose another fragment.
![title-not-update-after-rotate](https://cloud.githubusercontent.com/assets/1776084/6996229/ff4c45c8-db2f-11e4-97ce-b96325877766.png)

**Another possible issue:**
After rotation, the title fonts become too small.
![rotate-title-font](https://cloud.githubusercontent.com/assets/1776084/6996232/0c8e5d84-db30-11e4-90ce-86a41d7a3aa5.png)
![rotate-title-font2](https://cloud.githubusercontent.com/assets/1776084/6996234/10b6a7c2-db30-11e4-9bf7-d598250b94d2.png)

Tested on Samsung Note 4 ATT version.

**Comment by robertwgh** [comment]
I have found the problem.

In `activities\NavigationDrawerActivity.java`,

```java
    private void initFragment(Bundle savedInstanceState) {
        if (mNavigationDrawerItems.size() <= 0) return;

        int fragmentPosition;
        boolean isSavedInstanceState = false;
        if (savedInstanceState != null) {
            isSavedInstanceState = true;
            fragmentPosition = savedInstanceState.getInt("current_fragment_position", 0);
        } else fragmentPosition = defaultNavigationDrawerItemSelectedPosition();

        if (fragmentPosition < 0 || fragmentPosition >= mNavigationDrawerItems.size()) {
            fragmentPosition = 0;
        }

        ListItem item = mNavigationDrawerItems.get(fragmentPosition);
        if (item instanceof NavigationDrawerListItemTopFragment) {
            if (!isSavedInstanceState) {
                getSupportFragmentManager()
                        .beginTransaction()
                        .add(R.id.fragment_container,
                                ((NavigationDrawerListItemTopFragment) item).getFragment())
                        .commit();

                // Here is the bug
                mCurrentItem = (NavigationDrawerListItemTopFragment) item;
                mCurrentItemPosition = (getNavigationDrawerAccountsHandler() == null ? 0 : 1) +
                        fragmentPosition;
            }
            mDrawerListView.setItemChecked(mCurrentItemPosition, true);
            replaceTitle(item.getTitle());
```

When a rotation happened, the condition `if (!isSavedInstanceState) ` is true, so the `mCurrentItem` and `mCurrentItemPosition` is not properly initialized. 

Therefore, when we open the drawer and close it:
```java
@Override
            public void onDrawerClosed(View view) {
                super.onDrawerClosed(view);

                if (mCurrentItem != null) replaceTitle(mCurrentItem.getTitle());
            }
```

Since `mCurrentItem` is null, the title is not replaced.

I moved two lines out of the if statement, and that seems to fix the problem,
```java
            if (!isSavedInstanceState) {
                getSupportFragmentManager()
                        .beginTransaction()
                        .add(R.id.fragment_container,
                                ((NavigationDrawerListItemTopFragment) item).getFragment())
                        .commit();
                //mCurrentItem = (NavigationDrawerListItemTopFragment) item;
                //mCurrentItemPosition = (getNavigationDrawerAccountsHandler() == null ? 0 : 1) +
                //        fragmentPosition;
            }
            mCurrentItem = (NavigationDrawerListItemTopFragment) item;
            mCurrentItemPosition = (getNavigationDrawerAccountsHandler() == null ? 0 : 1) +
                    fragmentPosition;
            mDrawerListView.setItemChecked(mCurrentItemPosition, true);
            replaceTitle(item.getTitle());
        }
```

**Comment by robertwgh** [comment]
The toolbar font size issue is fixed by the following steps.

**In style.xml of the material design library, add:**
```xml
<style name="ToolBarTextAppearance" parent="@android:style/TextAppearance.Medium">
        <item name="android:textSize">@dimen/toolbar_text_size</item>
</style>
```

**In dimen.xml, add:**
```xml
<dimen name="toolbar_text_size">20sp</dimen>
```

It seems that the original font size of toolbar was 22sp. But after several experiments, I think 20sp fits my need best.

**Finally, in AActivity.java, add one line to apply the style to the title:**
```java
public void onCreate(Bundle savedInstanceState, int contentView) {
        super.onCreate(savedInstanceState);
        setContentView(contentView);

        mToolbar = (Toolbar) findViewById(R.id.toolbar);
        mToolbar.setTitleTextColor(getResources().getColor(android.R.color.white));
        // Add the following line.
        mToolbar.setTitleTextAppearance(this, R.style.ToolBarTextAppearance);
        setSupportActionBar(mToolbar);
        getSupportActionBar().setDisplayShowHomeEnabled(true);
    }
```

Then I can have consistent font before or after the screen rotation.

**Comment by DenisMondon** [comment]
Hi! Thanks for your issue :)

1) I will fix the bug with the wrong navigationDrawer title for the next release:)
2) I think it's not an issue that the font size in landscape mode is smaller than in portrait mode.
You can try it with Gmail for example and you will have the same result. Tell me if I did not understand your problem.

Thank you again!

**Comment by robertwgh** [comment]
I think the font size is still an issue. It looks very bad in landscape mode. 
As you have said, Google's official apps also show the same behavior. But I think it might be a bug or something. I have reported this as an issue to Android developer bug report. 

https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=163255

Thanks for your excellent library. It is quite useful, and easy to use as well.

**Comment by robertwgh** [comment]
Interesting. The android team replies the issue report with "workingAsIntended".
It seems that they think it is the right behavior to make the tile smaller for landscape mode. But to me, it looks weird. Anyways, it is not a issue in your library. But I think this might get fixed in a future version of Android ...

thanks.

**Comment by DenisMondon** [comment]
I think it's just to give more space to the user in landscape mode. But thank you very much and I'm available if you have some other comments! :)

Denis

**Comment by DenisMondon** [comment]
I released the new version on the Play Store (version 2.0). Normally, this screen rotation problem is fixed.
Thank you again!

Denis

**Comment by robertwgh** [comment]
I checked the google Play store, the new app has not shown up yet. Probably need some time. 

Regarding to the title font size for landscape mode, I have some new findings.
I just updated my phone to Lollipop (Note 4 ATT version).
I found out that even for Google applications, such as Play Store, Gmail, Play movie, Play books, Google Drive, Music, and so on. The behavior is very different. 

For example, in the following applications, the font size of port and land modes are the same (you can see the attached pictures for details):
- System settings
- Play Store
- Play Book
- Photos
- Play Movie
- And others

For some other applications, the font will be very small in land mode:
-Play music
- gmail
- youtube
- others

This is really something bad for Android, the UI design is not consistent, and the user experience will be very bad and frustrated. 

But after comparing the visual effect, I decide to use the consistent font size for both port and land mode, in my own applications. 

![settings](https://cloud.githubusercontent.com/assets/1776084/7109897/b855cdf0-e15c-11e4-808f-d245410ba906.png)
![settings2](https://cloud.githubusercontent.com/assets/1776084/7109896/b8532906-e15c-11e4-9e41-c984c3a75ab5.png)

![play1](https://cloud.githubusercontent.com/assets/1776084/7109899/c5b83bae-e15c-11e4-9c8a-1e388a5066e3.png)
![play2](https://cloud.githubusercontent.com/assets/1776084/7109900/c5ba5fba-e15c-11e4-9913-9deb4ee1eaf9.png)

![book1](https://cloud.githubusercontent.com/assets/1776084/7109903/cbb501fe-e15c-11e4-8877-0bf3c673de39.png)
![book2](https://cloud.githubusercontent.com/assets/1776084/7109908/cbd7f808-e15c-11e4-818c-8508ab3eaaa0.png)

![movie1](https://cloud.githubusercontent.com/assets/1776084/7109904/cbca66f2-e15c-11e4-92bf-ea0234cc636b.png)
![movie2](https://cloud.githubusercontent.com/assets/1776084/7109906/cbd71000-e15c-11e4-89c8-2490e2b11086.png)

![photos1](https://cloud.githubusercontent.com/assets/1776084/7109907/cbd778d8-e15c-11e4-84db-a5a6fa7ffefc.png)
![photos2](https://cloud.githubusercontent.com/assets/1776084/7109905/cbd592d4-e15c-11e4-90c3-75f6e4dfd940.png)
