### ISSUE TITLE
Navigation UP ParentActivity button

### ISSUE THREAD

**Issue by harishannam** [DenisMondon/material-design-library#31]
Hi,

I have mentioned "parentActivityName" in my manifest for an activity. But still the new activity actionbar does not show a back arrow to navigate to the parent activity. 

Action bar just shows the title. No arrow to go to previous activity. Any idea how to get it ? Your example activities also do not show parent activity button.

**Comment by harishannam** [comment]
Sorry, beginner here. 

getSupportActionBar().setDisplayHomeAsUpEnabled(true);

solved the issue for me. Thanks alot.

I was also searching for getting action bar in my own activity, for those people can refer this link.

https://github.com/DenisMondon/material-design-library/issues/13

**Comment by DenisMondon** [comment]
Is it ok ? I saw that you also created and closed this issue: https://github.com/DenisMondon/material-design-library/issues/31#issuecomment-127566288

Denis

**Comment by DenisMondon** [comment]
Sorry my bad, I did not see that this one was closed...

Have a good day :)
