### ISSUE TITLE
How to switch fragment one from another inside navigation drawer activity without having it inside navigationtophandler or navigatiobothandler ?

### ISSUE THREAD

**Issue by dadja** [DenisMondon/material-design-library#33]
Hello Denis,
first of all i want to say thank you for this awesome library :) ; it helps a lot !
my issue si this: 
i want to switch from a fragment to another inside the navigationdraweractivity without using navigationtophandler and/or navigationbottomhandler i want it to appear in the in mai screen of the activity; how can i achieve it using you navigationdraweractivity please;
thank you

**Comment by DenisMondon** [comment]
Hi :)

Thank you!
If I well understand, you have a fragment in your top handler with a button inside of it for example. When you click on this button, you want to replace this fragment with another one that is not in the top handler?

**Comment by dadja** [comment]
HI!
yep exactly thats my problem right now ;as usually we do sue fragmenttransaction to attempt it by passing the view where the fragment will be shown and the fragment that should be sent there, i'm pretty confused on how to attempt to do so :)

**Comment by DenisMondon** [comment]
You can do this in your fragment:
```java
getActivity().getSupportFragmentManager().beginTransaction().replace(com.blunderer.materialdesignlibrary.R.id.fragment_container, your_new_fragment).commit();
```
It is not beautiful but it works :)

Denis

**Comment by dadja** [comment]
no matter if its not beautiful yet :) it works :)  Big thanks !!


2015-08-10 14:46 GMT+00:00 Denis Mondon <notifications@github.com>:

> You can do this in your fragment:
>
> getActivity().getSupportFragmentManager().beginTransaction().replace(com.blunderer.materialdesignlibrary.R.id.fragment_container, your_new_fragment).commit();
>
> It is not beautiful but it works :)
>
> Denis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DenisMondon/material-design-library/issues/33#issuecomment-129479058>
> .
>



-- 


Best Regards Dadja Matiasso BASSOU


Sofware Engineer
Indie Game Developer
Tel:+221774627966
*youtube channel :* http://www.youtube.com/reptx
E*mail:* bassoudadja@gmail.com <email%3Abassoudadja@gmail.com>
*Skype:* apocalypse003
Twitter:@Reptx

**Comment by DenisMondon** [comment]
Good :) I close the issue :)
