### ISSUE TITLE
Setting defaultNavigationDrawerItemSelectedPosition Manually

### ISSUE THREAD

**Issue by ogulcan** [DenisMondon/material-design-library#35]
Hi there,

First of all thanks for library. I've an issue. I'm forcing some fragments manually. It looks like: 
`getActivity().getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container, new SSSFragment()).commit();`

That fragment is already on top handler. But when app replaced, selected position is still looking old value. Is there any way trigger defaultNavigationDrawerItemSelectedPosition manually? Or I would be ok if replacing fragment_container with updating selected position is possible.

**Comment by DenisMondon** [comment]
Hi,

Yeah you can call performNavigationDrawerItemClick(int position) =>
In your NavigationDrawerActivity:
```java
performNavigationDrawerItemClick(2);
```
In your Fragment that is inside your NavigationDrawerActivity:
```java
((NavigationDrawerActivity) getActivity()).performNavigationDrawerItemClick(2);
```

Denis

**Comment by ogulcan** [comment]
Thank you.
