### ISSUE TITLE
NavigationDrawer: Provide support for multiple screen sizes

### ISSUE THREAD

**Issue by robertwgh** [DenisMondon/material-design-library#4]
Could you please add support for multiple screen sizes?
Current settings are fixed. It looks good on phones, but not on tablets. 
For tablet, the fonts look tooo small, the gap between rows in the drawer is too narrow. 

I have to make changes to the library to support multiple screen sizes (different resolution, DPI). One way is to either add dimen.xml for different dpis, for example

`values`
`values-sw600dp`
`values-sw720dp`

Another way is to add a few APIs and to allow the developer to set the dimension values using those APIs.

**Comment by DenisMondon** [comment]
Hi robertwgh!

Yeah, I have a lot of work to do with devices compatibility. I will add some dimensions in the next release to support multiple devices.

Just to know, you have a 10 inches device ?
Because on my Nexus 7 (7 inches), it looks pretty well (not perfect but well).

Thank you!
Denis

**Comment by robertwgh** [comment]
It now looks good on my tablet. 
Such a quick turn around. Thanks for update. 

By the way, I also noticed that the font size for landscape mode is much nicer now. Good update.

The following is a screenshot on Samsung Note 10.1 2014 Edition, 2556x1440.
![note10 1](https://cloud.githubusercontent.com/assets/1776084/7126434/ec3b8876-e1ed-11e4-9c8e-05e6ae28f9dc.png)

**Comment by DenisMondon** [comment]
Thank you! :)

Denis
