### ISSUE TITLE
Library jar file

### ISSUE THREAD

**Issue by Rahman-94** [DenisMondon/material-design-library#42]
I don't know how to use the source without it's jar file. can anyone help me with this ?

**Comment by Rahman-94** [comment]
I tried to use the source and import codes directly to my project but i encountered lots of errors that i couldn't solve. I was using android studio. i fixed package issues but there were still unsolved errors. what should I do ?

**Comment by bibek011** [comment]
Ass the provided dependency in your build.gradle
