### ISSUE TITLE
Request: Drawer account area

### ISSUE THREAD

**Issue by JesperChristensen** [DenisMondon/material-design-library#6]
Hi Denis,
Allow me to complement you on a great job developing this Library
It's very easy to use.

I have a little request.
Could you point me in the direction of which classes i should change, in order to get the result below. 
I like the account option, but images and quick select dosn't make much sense in the app I'm developing.

Thanks again for a great libray

![2015-04-10_12-37-09](https://cloud.githubusercontent.com/assets/11884450/7086221/813aa7bc-df7e-11e4-9763-ed02752dde3b.png)

**Comment by DenisMondon** [comment]
Hi Jesper!

Thank you for your message! :D

I think it is a good feature to add in my library so it will be available on the next release I hope :)
I will let you know ;)

Denis

**Comment by DenisMondon** [comment]
Hi!

You can use the new release to implement the "Small Accounts Layout" in your NavigationDrawer!

Just add ".enableSmallAccountsLayout()" to your NavigationDrawerAccountsHandler like that:

    @Override
    public NavigationDrawerAccountsHandler getNavigationDrawerAccountsHandler() {
        return new NavigationDrawerAccountsHandler(this)
                .enableSmallAccountsLayout()
                .addAccount("Profile #1", "profile1@gmail.com",
                        R.drawable.profile1, R.drawable.profile1_background)
                .addAccount("Profile #2", "profile2@gmail.com",
                        R.drawable.profile2, R.drawable.profile2_background);
    }

Hope you'll enjoy it!

Denis

**Comment by JesperChristensen** [comment]
Hi Denis,

it works exactly as I hoped. thanks for a great library

br
jesper

**Comment by DenisMondon** [comment]
Thank you!

Denis
