### ISSUE TITLE
Add more addItem() variations for NavigationDrawerTopHandler and NavigationDrawerBottomHandler

### ISSUE THREAD

**Issue by robertwgh** [DenisMondon/material-design-library#8]
Denis, 

I have another suggestion regarding to the addItem() functions.
Currently, all the variations use string resource as the item title/header. 
```Java
public NavigationDrawerTopHandler addItem(int titleResource,
                                              int iconResource,
                                              Fragment fragment) {
        NavigationDrawerListItemTopFragment item = new NavigationDrawerListItemTopFragment();
        item.setTitle(mContext, titleResource);
        item.setIcon(mContext, iconResource);
        item.setFragment(fragment);
        mItems.add(item);
        return this;
    }
```
However, this prevents the dynamic information being used as titles.  
In my application, the header/title strings are retrieved dynamically by querying the device. So I have to modify the TopHandler and BottomHandler and implement addItem() with java string as input argument. 

So I suggest that you add the addItem(string title, ...) versions to make the library more flexible. 
Thanks.

**Comment by DenisMondon** [comment]
Hi!

Oh yeah, it's a mistake!
I will update the library for the next release :)

Thank you for the issue :)

Denis
